import Head from 'next/head'
import { useEffect } from 'react'
import Follow from '../components/Body/Follow'
import Story from '../components/Body/Story'
import TotalFeed from '../components/Body/TotalFeed'
import Navbar from '../components/Navbar/Navbar'
import { auth } from '../firebase';
import { useRouter } from 'next/router';


export default function Home() {

  return (
    <div >
      <Head>
        <title>Instagram</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/insta.ico" />
      </Head>

      <div className='navContainer'> 
        <div className='navbar'>
          <Navbar />
        </div>
        <div className='flex'>
          <div className='w-1/4'></div>
          <div className='w-3/5'>
            <Story />
            <TotalFeed />
          </div>
          <div className='w-2/5 '>
            <Follow />
          </div>
          <div className='w-1/4'></div>
        </div>
      </div>
    </div>
  )
}
